# Generated by Django 4.1.7 on 2023-03-05 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('costs', models.FloatField()),
                ('verion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('costs', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('game', models.ManyToManyField(to='property.game')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.mail')),
            ],
        ),
    ]
