# Generated by Django 4.1.7 on 2023-02-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dislike',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
