# Generated by Django 4.1.7 on 2023-02-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_programer_languages_tennis_payers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programer_languages',
            name='processing',
        ),
        migrations.RemoveField(
            model_name='programer_languages',
            name='speed',
        ),
    ]
